require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` from `react-native.config.js`
#
# ```javascript
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   },
# };
# ```
flipperkit_version = "0.182.0"

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SilhouetteWorkflow' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SilhouetteWorkflowTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Configuraciones específicas para Silhouette Workflow
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Configurar versión mínima de iOS
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        
        # Configurar arquitectura
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
        config.build_settings['VALID_ARCHS'] = 'arm64 arm64e x86_64'
        
        # Configurar el bundle identifier
        config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.silhouette.workflow'
        
        # Configurar código de signing
        if ENV['CI']
          config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Distribution'
          config.build_settings['CODE_SIGNING_REQUIRED'] = 'YES'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
        end
        
        # Configurar optimizaciones de build
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['ENABLE_TESTABILITY'] = 'NO'
        config.build_settings['ENABLE_NS_ASSERTIONS'] = 'NO'
        
        # Configurar configuración de build para release
        if config.name == 'Release'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL[sdk=iphonesimulator*]'] = '-Onone'
        end
        
        # Configurar para React Native
        if target.name == 'react-native-camera'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            'RNCAMERA_USE_FRAMEWORK=1'
          ]
        end
        
        # Configurar para React Native Vector Icons
        if target.name == 'RNVectorIcons'
          config.build_settings['USER_HEADER_SEARCH_PATHS'] ||= [
            '$(inherited) "$(SRCROOT)/../../../node_modules/react-native-vector-icons"'
          ]
        end
      end
    end
  end
end